---
driver:
  name: docker
  hostname: rundeck.ci.local
  use_sudo: false

provisioner:
  name: salt_solo
  salt_install: bootstrap
  salt_bootstrap_url: https://bootstrap.saltstack.com
  salt_version: latest
  require_chef: false
  log_level: error
  formula: rundeck
  grains:
    noservices: true
  state_top:
    base:
      "*":
        - rundeck
  pillars:
    top.sls:
      base:
        "*":
          - rundeck

verifier:
  name: inspec
  sudo: true


platforms:
  - name: <%=ENV['PLATFORM'] ||  'saltstack-ubuntu-xenial-salt-stable' %>
    driver_config:
      image: <%=ENV['PLATFORM'] || 'epcim/salt:saltstack-ubuntu-xenial-salt-stable'%>
      platform: ubuntu

suites:
  - name: server
    provisioner:
      pillars-from-files:
        rundeck.sls: tests/pillar/server.sls
  - name: client
    provisioner:
      pillars-from-files:
        rundeck.sls: tests/pillar/client.sls

# vim: ft=yaml sw=2 ts=2 sts=2 tw=125
